### PR TITLE
some constants added to Kroll

### PR DESCRIPTION
**Pull request by AppWerft**

### CODE REVIEW

**Comment by m1ga** [comment]
What are they used for?

**Comment by m1ga** [comment]
please do one commit with all the needed files and provide some documentation and an example. The title and the commit message is not very helpful

**Comment by AppWerft** [comment]
allowedNetworks added global to module and to startDownload added
some new convenience methods added

roadmap: remove from download.
Background: If you remove files from folder with an other manager you need a possibility to remove from manager to give a posibility to redownload.

**Comment by m1ga** [comment]
Please finish the PR in your fork first before you do the PR! I don't know when you are done and it sends an email all the time

**Comment by AppWerft** [comment]
OK

**Pull request closed without merging**
